---
- name: Converge
  hosts: all
  vars:
    ohmyzsh_users:
      - username: user1
      - username: user2
  pre_tasks:
    - name: Create test users
      user:
        name: "{{ item.username }}"
        state: present
      with_items: '{{ ohmyzsh_users }}'
      changed_when: false
  roles:
    - role: ansible-ohmyzsk
